version: "3.4"

services:
  php:
    build:
      context: .
      target: app_php
    restart: always
    volumes:
      - php_socket:/var/run/php
      - ./var/log:/srv/app/var/log/
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  nginx:
    build:
      context: .
      target: app_nginx
    restart: always
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - php_socket:/var/run/php
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    depends_on:
      - php

volumes:
  php_socket:

